# Docker- compose
version: '3'
services:
  db:
    image: postgres:9.6
    container_name: proyecto_apis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: proyecto_apis
    volumes:
      - ./data/postgres:/var/lib/postgresq l/data